name: Release
on: [push]

jobs:
  build:
    runs-on: MacOS
    steps:
      - name: 增量更新代码仓库
        run: |
          REPO_NAME=$(basename "${GITHUB_REPOSITORY}")
          BRANCH_NAME="${GITHUB_REF_NAME}"
          CI_DIR="/tmp/${REPO_NAME}_${BRANCH_NAME}"

          if [ ! -d "${CI_DIR}" ]; then
            git clone -b "${BRANCH_NAME}" ssh://git@127.0.0.1:222/${GITHUB_REPOSITORY}.git "${CI_DIR}"
          else
            cd "${CI_DIR}"
            git reset --hard HEAD
            git clean -df
            git pull origin "${BRANCH_NAME}" --rebase
          fi

      - name: 执行构建脚本
        run: |
          REPO_NAME=$(basename "${GITHUB_REPOSITORY}")
          BRANCH_NAME="${GITHUB_REF_NAME}"
          CI_DIR="/tmp/${REPO_NAME}_${BRANCH_NAME}"

          cd "${CI_DIR}"
          chmod +x action_build.sh
          ./action_build.sh

      - name: 上传产物
        run: |
          REPO_NAME=$(basename "${GITHUB_REPOSITORY}")
          BRANCH_NAME="${GITHUB_REF_NAME}"
          CI_DIR="/tmp/${REPO_NAME}_${BRANCH_NAME}"

          cd "${CI_DIR}"
          if [ -f miniping-linux-x86_64 ]; then
            echo "miniping-linux-x86_64:$(ls -lh miniping-linux-x86_64 | awk '{print $5}')" >> artifact_info.txt
          fi